---
title: "About This Project"
---
This project presents a cleaned and visualized Yu-Gi-Oh! card dataset using R, Quarto, ggplot2, and Plotly.  

The goal is to create a website where you can search up a card and see the cards information and be able to create a deck.

---

## Data Source

- Original dataset: https://www.kaggle.com/datasets/archanghosh/yugioh-database
- Data set owners: Archan Ghosh and Madhurima Maji

This data contains:

- Card name  
- Card type (Monster, Spell, Trap)  
- Attribute (DARK, LIGHT, FIRE, Mech,)  
- Attack and defense values  
- Level, rank, and other stats  

All visuals and summaries on this site come from the cleaned dataset and card
images are taken from google.

---

## Work

- Standardized column
- Removed or converted missing values  
- Separated combined fields (ATK/DEF and ATK/LINK)  
- Converted level, rank, and pendulum scale to numeric values  
- Cleaned text fields (rarity, card type, attribute)
- Make photos intractable
- Create visuals for data

## Links
- https://www.kaggle.com/datasets/archanghosh/yugioh-database
- https://quarto.org/docs/output-formats/html-lightbox-figures.html
- https://outof.games/realms/yugioh/cards/
- https://codepen.io/nguyenanhtuan/pen/abQMrBY

[Back to Home](index.qmd)
